base_local_planner: potbot_nav/PersonalSpaceDWAROS

PersonalSpaceDWAROS:

# Robot Configuration Parameters
  max_vel_x: 0.2
  min_vel_x: 0    # 並進速度の最小値 0以上にするとバック走行しなくなる

  max_vel_y: 0.0
  min_vel_y: 0.0

# The velocity when robot is moving in a straight line
  max_vel_trans:  1.0
  min_vel_trans:  0.11

  max_vel_theta: 2.75
  min_vel_theta: 1.37

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2 

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.17
  latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 1.5
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  controller_frequency: 20.0

# Trajectory Scoring Parameters
  path_distance_bias: 0.01
  goal_distance_bias: 1
  occdist_scale: 1
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  lf_scale : 4.31
  ls_scale : 0.68
  ps_weight : 50
  MAX_X : 10
  MIN_X : 0.0
  MAX_Y : 0.95
  MIN_Y : -0.95

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
